services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "scan-db"
    ports:
        - "127.0.0.1:5432:5432"
    restart: always

  domain_discovery:
    image: "ghcr.io/soccer-project-dep/vulnman-domain-discovery:main"
    container_name: domain_discovery
    environment:
      DB_CONN_STR: "postgresql://postgres:postgres@postgres_db:5432/scan-db"
    entrypoint: poetry run python src/main.py --target "pentest01.csirt.muni.cz"
    depends_on:
      - postgres_db

#  nuclei_orchestrator:
#    image: ghcr.io/soccer-project-dep/vulnman-nuclei-orchestrator
#    container_name: nuclei_orchestrator
#    environment:
#      DB_CONNECTION_STRING: postgresql://postgres:postgres@postgres_db:5432/scan-db
#      GL_TOKEN: <your-gitlab-token>
#    entrypoint: poetry run nuclei-scan-runner --config ./configs/testing-config.toml



    
