services:
  nuclei_orchestrator:
    image: vulnman/nuclei-orchestrator:latest
    container_name: nuclei_orchestrator
    entrypoint: poetry run nuclei-scan-runner --config /vulnman-nuclei-orchestrator/configs_new/${CONFIG_FILE}
    volumes:
      - .vulnman_data/nuclei_orchestrator_logs:/var/log/vulnman-nuclei/
      - ./nuclei_orchestrator_configs:/vulnman-nuclei-orchestrator/configs_new
    networks:
      - scan_network
    env_file:
      - vulnman.env

networks:
  scan_network:
    name: scan_network
    driver: bridge
    external: true
