---
- name: Remove existing Go symlink
  ansible.builtin.file:
    path: /usr/bin/go
    state: absent

- name: Remove existing Go directory
  ansible.builtin.file:
    path: /usr/lib/go
    state: absent

- name: Remove apt golang
  ansible.builtin.apt:
    name: golang
    state: absent

- name: Download Go {{ install_golang_version }}
  ansible.builtin.get_url:
    url: https://go.dev/dl/go{{ install_golang_version }}.linux-amd64.tar.gz
    dest: /tmp/golang{{ install_golang_version }}.tar.gz
    mode: u=rw,g=r,o=

- name: Extract Go compiler to /usr/lib
  ansible.builtin.unarchive:
    src: /tmp/golang{{ install_golang_version }}.tar.gz
    dest: /usr/lib/
    copy: false

- name: Save version to file
  ansible.builtin.copy:
    content: "{{ install_golang_version }}"
    dest: /usr/lib/go.version

- name: Create symlink to Go compiler
  ansible.builtin.file:
    src: /usr/lib/go/bin/go
    dest: /usr/bin/go
    state: link
