---
- name: Copy credentials template
  ansible.builtin.template:
    src: .env.j2
    dest: /opt/dd/.env
    mode: "0600"
    owner: "{{ domain_discovery_nonroot_user }}"
    group: "{{ domain_discovery_nonroot_user }}"
