---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv
    - python3-pip
    - jq
    - libpq-dev
    - postgresql-client
    - python3-click

- name: Install pipx
  ansible.builtin.pip:
    name: pipx
    state: present
  ignore_errors: true

- name: Install pipx with --break-system-packages
  ansible.builtin.pip:
    name: pipx
    state: present
    extra_args: --break-system-packages
  ignore_errors: true

- name: Run ensurepath
  ansible.builtin.command: "pipx ensurepath"

- name: Install bbot dependencies
  ansible.builtin.command: "bbot --install-all-deps"
  changed_when: false
  ignore_errors: true

- name: Check if bbot is installed
  ansible.builtin.command: "bbot --version"
  become: false
  become_user: "{{ domain_discovery_nonroot_user }}"
  register: bbot_version
  failed_when: bbot_version.rc != 0
