---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-venv
    - python3-pip
    - jq
    - libpq-dev
    - postgresql-client
    - python3-click

- name: Install bbot via pip
  ansible.builtin.pip:
    name: bbot
    state: present

- name: Install bbot dependencies
  ansible.builtin.command: "bbot --install-all-deps"
  changed_when: false
