---
- name: Copy credentials to .env
  ansible.builtin.template:
    src: env.j2
    dest: /home/{{ nuclei_scanner_nonroot_user }}/vulnman-nuclei/.env
    owner: "{{ nuclei_scanner_nonroot_user }}"
    group: "{{ nuclei_scanner_nonroot_user }}"
    mode: u=rw,o=,g=
    