---
- name: Setup SystemD service
  tags:
    - nuclei_systemd
  ansible.builtin.import_tasks: systemd.yml

- name: Copy files
  ansible.builtin.copy:
    src: "../../../{{ item }}"
    dest: /opt/nuclei-orchestrator/
    mode: "0644"
    owner: root
    group: root
  with_items:
    - nuclei_orchestrator.compose.yml
    - vulnman.env
    - nuclei_orchestrator_configs/
