---
- name: Prepare machine
  ansible.builtin.import_tasks: prepare.yml

- name: Install nuclei
  ansible.builtin.import_tasks: install_nuclei.yml

- name: Setup credentials
  ansible.builtin.import_tasks: credentials_setup.yml

- name: Setup SystemD service
  tags:
    - nuclei_systemd
  ansible.builtin.import_tasks: systemd.yml

- name: Setup Logrotate config
  ansible.builtin.import_tasks: logrotate.yml
