---
- name: Copy the files over
  vars:
    type: "{{ item.type }}"
    persistent: "{{ item.persistent }}"
    calendar: "{{ item.calendar }}"
  block:
    - name: Copy systemd service
      ansible.builtin.template:
        src: nuclei-scan.timer.j2
        dest: /etc/systemd/system/nuclei-{{ item.type }}.timer
        owner: root
        group: root
        mode: g=r,o=r

    - name: Copy systemd timer
      ansible.builtin.template:
        src: nuclei-scan.service.j2
        dest: /etc/systemd/system/nuclei-{{ item.type }}.service
        owner: root
        group: root
        mode: g=r,o=r
