- name: Disable postgresql service
  ansible.builtin.service:
    name: postgresql
    state: stopped
    enabled: false
  become: true
  failed_when: false

- name: Check 5432 port, if open skip import else import db.yml
  ansible.builtin.wait_for:
    port: 5432
    state: started
    timeout: 2
  register: result
  ignore_errors: true

- name: Import db.yml
  ansible.builtin.include_tasks: db.yml
  when: result.failed
